package clientTS;

/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-08-23")
public class CommonManageService {

  public interface Iface {

    public void ServiceRequest(CommonManageReqInfo reqInfo) throws org.apache.thrift.TException;

    public void ServiceReply(CommonManageReply repInfo) throws org.apache.thrift.TException;

    public CommonManageReply ServiceReqAndReply(CommonManageReqInfo reqInfo) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void ServiceRequest(CommonManageReqInfo reqInfo, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler) throws org.apache.thrift.TException;

    public void ServiceReply(CommonManageReply repInfo, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler) throws org.apache.thrift.TException;

    public void ServiceReqAndReply(CommonManageReqInfo reqInfo, org.apache.thrift.async.AsyncMethodCallback<CommonManageReply> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public void ServiceRequest(CommonManageReqInfo reqInfo) throws org.apache.thrift.TException
    {
      send_ServiceRequest(reqInfo);
    }

    public void send_ServiceRequest(CommonManageReqInfo reqInfo) throws org.apache.thrift.TException
    {
      ServiceRequest_args args = new ServiceRequest_args();
      args.setReqInfo(reqInfo);
      sendBaseOneway("ServiceRequest", args);
    }

    public void ServiceReply(CommonManageReply repInfo) throws org.apache.thrift.TException
    {
      send_ServiceReply(repInfo);
    }

    public void send_ServiceReply(CommonManageReply repInfo) throws org.apache.thrift.TException
    {
      ServiceReply_args args = new ServiceReply_args();
      args.setRepInfo(repInfo);
      sendBaseOneway("ServiceReply", args);
    }

    public CommonManageReply ServiceReqAndReply(CommonManageReqInfo reqInfo) throws org.apache.thrift.TException
    {
      send_ServiceReqAndReply(reqInfo);
      return recv_ServiceReqAndReply();
    }

    public void send_ServiceReqAndReply(CommonManageReqInfo reqInfo) throws org.apache.thrift.TException
    {
      ServiceReqAndReply_args args = new ServiceReqAndReply_args();
      args.setReqInfo(reqInfo);
      sendBase("ServiceReqAndReply", args);
    }

    public CommonManageReply recv_ServiceReqAndReply() throws org.apache.thrift.TException
    {
      ServiceReqAndReply_result result = new ServiceReqAndReply_result();
      receiveBase(result, "ServiceReqAndReply");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "ServiceReqAndReply failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void ServiceRequest(CommonManageReqInfo reqInfo, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      ServiceRequest_call method_call = new ServiceRequest_call(reqInfo, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class ServiceRequest_call extends org.apache.thrift.async.TAsyncMethodCall<Void> {
      private CommonManageReqInfo reqInfo;
      public ServiceRequest_call(CommonManageReqInfo reqInfo, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, true);
        this.reqInfo = reqInfo;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("ServiceRequest", org.apache.thrift.protocol.TMessageType.ONEWAY, 0));
        ServiceRequest_args args = new ServiceRequest_args();
        args.setReqInfo(reqInfo);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public Void getResult() throws org.apache.thrift.TException {
        if (getState() != State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return null;
      }
    }

    public void ServiceReply(CommonManageReply repInfo, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      ServiceReply_call method_call = new ServiceReply_call(repInfo, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class ServiceReply_call extends org.apache.thrift.async.TAsyncMethodCall<Void> {
      private CommonManageReply repInfo;
      public ServiceReply_call(CommonManageReply repInfo, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, true);
        this.repInfo = repInfo;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("ServiceReply", org.apache.thrift.protocol.TMessageType.ONEWAY, 0));
        ServiceReply_args args = new ServiceReply_args();
        args.setRepInfo(repInfo);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public Void getResult() throws org.apache.thrift.TException {
        if (getState() != State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return null;
      }
    }

    public void ServiceReqAndReply(CommonManageReqInfo reqInfo, org.apache.thrift.async.AsyncMethodCallback<CommonManageReply> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      ServiceReqAndReply_call method_call = new ServiceReqAndReply_call(reqInfo, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class ServiceReqAndReply_call extends org.apache.thrift.async.TAsyncMethodCall<CommonManageReply> {
      private CommonManageReqInfo reqInfo;
      public ServiceReqAndReply_call(CommonManageReqInfo reqInfo, org.apache.thrift.async.AsyncMethodCallback<CommonManageReply> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.reqInfo = reqInfo;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("ServiceReqAndReply", org.apache.thrift.protocol.TMessageType.CALL, 0));
        ServiceReqAndReply_args args = new ServiceReqAndReply_args();
        args.setReqInfo(reqInfo);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public CommonManageReply getResult() throws org.apache.thrift.TException {
        if (getState() != State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_ServiceReqAndReply();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, java.util.Map<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> java.util.Map<String,  org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> getProcessMap(java.util.Map<String, org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("ServiceRequest", new ServiceRequest());
      processMap.put("ServiceReply", new ServiceReply());
      processMap.put("ServiceReqAndReply", new ServiceReqAndReply());
      return processMap;
    }

    public static class ServiceRequest<I extends Iface> extends org.apache.thrift.ProcessFunction<I, ServiceRequest_args> {
      public ServiceRequest() {
        super("ServiceRequest");
      }

      public ServiceRequest_args getEmptyArgsInstance() {
        return new ServiceRequest_args();
      }

      protected boolean isOneway() {
        return true;
      }

      @Override
      protected boolean handleRuntimeExceptions() {
        return false;
      }

      public org.apache.thrift.TBase getResult(I iface, ServiceRequest_args args) throws org.apache.thrift.TException {
        iface.ServiceRequest(args.reqInfo);
        return null;
      }
    }

    public static class ServiceReply<I extends Iface> extends org.apache.thrift.ProcessFunction<I, ServiceReply_args> {
      public ServiceReply() {
        super("ServiceReply");
      }

      public ServiceReply_args getEmptyArgsInstance() {
        return new ServiceReply_args();
      }

      protected boolean isOneway() {
        return true;
      }

      @Override
      protected boolean handleRuntimeExceptions() {
        return false;
      }

      public org.apache.thrift.TBase getResult(I iface, ServiceReply_args args) throws org.apache.thrift.TException {
        iface.ServiceReply(args.repInfo);
        return null;
      }
    }

    public static class ServiceReqAndReply<I extends Iface> extends org.apache.thrift.ProcessFunction<I, ServiceReqAndReply_args> {
      public ServiceReqAndReply() {
        super("ServiceReqAndReply");
      }

      public ServiceReqAndReply_args getEmptyArgsInstance() {
        return new ServiceReqAndReply_args();
      }

      protected boolean isOneway() {
        return false;
      }

      @Override
      protected boolean handleRuntimeExceptions() {
        return false;
      }

      public ServiceReqAndReply_result getResult(I iface, ServiceReqAndReply_args args) throws org.apache.thrift.TException {
        ServiceReqAndReply_result result = new ServiceReqAndReply_result();
        result.success = iface.ServiceReqAndReply(args.reqInfo);
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, java.util.Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> java.util.Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(java.util.Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("ServiceRequest", new ServiceRequest());
      processMap.put("ServiceReply", new ServiceReply());
      processMap.put("ServiceReqAndReply", new ServiceReqAndReply());
      return processMap;
    }

    public static class ServiceRequest<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, ServiceRequest_args, Void> {
      public ServiceRequest() {
        super("ServiceRequest");
      }

      public ServiceRequest_args getEmptyArgsInstance() {
        return new ServiceRequest_args();
      }

      public org.apache.thrift.async.AsyncMethodCallback<Void> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<Void>() {
          public void onComplete(Void o) {
          }
          public void onError(Exception e) {
            if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
            } else {
              _LOGGER.error("Exception inside oneway handler", e);
            }
          }
        };
      }

      protected boolean isOneway() {
        return true;
      }

      public void start(I iface, ServiceRequest_args args, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler) throws org.apache.thrift.TException {
        iface.ServiceRequest(args.reqInfo,resultHandler);
      }
    }

    public static class ServiceReply<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, ServiceReply_args, Void> {
      public ServiceReply() {
        super("ServiceReply");
      }

      public ServiceReply_args getEmptyArgsInstance() {
        return new ServiceReply_args();
      }

      public org.apache.thrift.async.AsyncMethodCallback<Void> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<Void>() {
          public void onComplete(Void o) {
          }
          public void onError(Exception e) {
            if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
            } else {
              _LOGGER.error("Exception inside oneway handler", e);
            }
          }
        };
      }

      protected boolean isOneway() {
        return true;
      }

      public void start(I iface, ServiceReply_args args, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler) throws org.apache.thrift.TException {
        iface.ServiceReply(args.repInfo,resultHandler);
      }
    }

    public static class ServiceReqAndReply<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, ServiceReqAndReply_args, CommonManageReply> {
      public ServiceReqAndReply() {
        super("ServiceReqAndReply");
      }

      public ServiceReqAndReply_args getEmptyArgsInstance() {
        return new ServiceReqAndReply_args();
      }

      public org.apache.thrift.async.AsyncMethodCallback<CommonManageReply> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<CommonManageReply>() {
          public void onComplete(CommonManageReply o) {
            ServiceReqAndReply_result result = new ServiceReqAndReply_result();
            result.success = o;
            try {
              fcall.sendResponse(fb, result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
            } catch (org.apache.thrift.transport.TTransportException e) {
              _LOGGER.error("TTransportException writing to internal frame buffer", e);
              fb.close();
            } catch (Exception e) {
              _LOGGER.error("Exception writing to internal frame buffer", e);
              onError(e);
            }
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TSerializable msg;
            ServiceReqAndReply_result result = new ServiceReqAndReply_result();
            if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
              return;
            } else if (e instanceof org.apache.thrift.TApplicationException) {
              _LOGGER.error("TApplicationException inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TApplicationException)e;
            } else {
              _LOGGER.error("Exception inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
            } catch (Exception ex) {
              _LOGGER.error("Exception writing to internal frame buffer", ex);
              fb.close();
            }
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, ServiceReqAndReply_args args, org.apache.thrift.async.AsyncMethodCallback<CommonManageReply> resultHandler) throws org.apache.thrift.TException {
        iface.ServiceReqAndReply(args.reqInfo,resultHandler);
      }
    }

  }

  public static class ServiceRequest_args implements org.apache.thrift.TBase<ServiceRequest_args, ServiceRequest_args._Fields>, java.io.Serializable, Cloneable, Comparable<ServiceRequest_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ServiceRequest_args");

    private static final org.apache.thrift.protocol.TField REQ_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("reqInfo", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ServiceRequest_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ServiceRequest_argsTupleSchemeFactory();

    public CommonManageReqInfo reqInfo; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      REQ_INFO((short)1, "reqInfo");

      private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // REQ_INFO
            return REQ_INFO;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.REQ_INFO, new org.apache.thrift.meta_data.FieldMetaData("reqInfo", org.apache.thrift.TFieldRequirementType.DEFAULT,
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CommonManageReqInfo.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ServiceRequest_args.class, metaDataMap);
    }

    public ServiceRequest_args() {
    }

    public ServiceRequest_args(
      CommonManageReqInfo reqInfo)
    {
      this();
      this.reqInfo = reqInfo;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ServiceRequest_args(ServiceRequest_args other) {
      if (other.isSetReqInfo()) {
        this.reqInfo = new CommonManageReqInfo(other.reqInfo);
      }
    }

    public ServiceRequest_args deepCopy() {
      return new ServiceRequest_args(this);
    }

    @Override
    public void clear() {
      this.reqInfo = null;
    }

    public CommonManageReqInfo getReqInfo() {
      return this.reqInfo;
    }

    public ServiceRequest_args setReqInfo(CommonManageReqInfo reqInfo) {
      this.reqInfo = reqInfo;
      return this;
    }

    public void unsetReqInfo() {
      this.reqInfo = null;
    }

    /** Returns true if field reqInfo is set (has been assigned a value) and false otherwise */
    public boolean isSetReqInfo() {
      return this.reqInfo != null;
    }

    public void setReqInfoIsSet(boolean value) {
      if (!value) {
        this.reqInfo = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case REQ_INFO:
        if (value == null) {
          unsetReqInfo();
        } else {
          setReqInfo((CommonManageReqInfo)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case REQ_INFO:
        return getReqInfo();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case REQ_INFO:
        return isSetReqInfo();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof ServiceRequest_args)
        return this.equals((ServiceRequest_args)that);
      return false;
    }

    public boolean equals(ServiceRequest_args that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_reqInfo = true && this.isSetReqInfo();
      boolean that_present_reqInfo = true && that.isSetReqInfo();
      if (this_present_reqInfo || that_present_reqInfo) {
        if (!(this_present_reqInfo && that_present_reqInfo))
          return false;
        if (!this.reqInfo.equals(that.reqInfo))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetReqInfo()) ? 131071 : 524287);
      if (isSetReqInfo())
        hashCode = hashCode * 8191 + reqInfo.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(ServiceRequest_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetReqInfo()).compareTo(other.isSetReqInfo());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetReqInfo()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reqInfo, other.reqInfo);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("ServiceRequest_args(");
      boolean first = true;

      sb.append("reqInfo:");
      if (this.reqInfo == null) {
        sb.append("null");
      } else {
        sb.append(this.reqInfo);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (reqInfo != null) {
        reqInfo.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class ServiceRequest_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public ServiceRequest_argsStandardScheme getScheme() {
        return new ServiceRequest_argsStandardScheme();
      }
    }

    private static class ServiceRequest_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<ServiceRequest_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, ServiceRequest_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
            break;
          }
          switch (schemeField.id) {
            case 1: // REQ_INFO
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.reqInfo = new CommonManageReqInfo();
                struct.reqInfo.read(iprot);
                struct.setReqInfoIsSet(true);
              } else {
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, ServiceRequest_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.reqInfo != null) {
          oprot.writeFieldBegin(REQ_INFO_FIELD_DESC);
          struct.reqInfo.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class ServiceRequest_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public ServiceRequest_argsTupleScheme getScheme() {
        return new ServiceRequest_argsTupleScheme();
      }
    }

    private static class ServiceRequest_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<ServiceRequest_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, ServiceRequest_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetReqInfo()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetReqInfo()) {
          struct.reqInfo.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, ServiceRequest_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.reqInfo = new CommonManageReqInfo();
          struct.reqInfo.read(iprot);
          struct.setReqInfoIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class ServiceReply_args implements org.apache.thrift.TBase<ServiceReply_args, ServiceReply_args._Fields>, java.io.Serializable, Cloneable, Comparable<ServiceReply_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ServiceReply_args");

    private static final org.apache.thrift.protocol.TField REP_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("repInfo", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ServiceReply_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ServiceReply_argsTupleSchemeFactory();

    public CommonManageReply repInfo; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      REP_INFO((short)1, "repInfo");

      private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // REP_INFO
            return REP_INFO;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.REP_INFO, new org.apache.thrift.meta_data.FieldMetaData("repInfo", org.apache.thrift.TFieldRequirementType.DEFAULT,
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CommonManageReply.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ServiceReply_args.class, metaDataMap);
    }

    public ServiceReply_args() {
    }

    public ServiceReply_args(
      CommonManageReply repInfo)
    {
      this();
      this.repInfo = repInfo;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ServiceReply_args(ServiceReply_args other) {
      if (other.isSetRepInfo()) {
        this.repInfo = new CommonManageReply(other.repInfo);
      }
    }

    public ServiceReply_args deepCopy() {
      return new ServiceReply_args(this);
    }

    @Override
    public void clear() {
      this.repInfo = null;
    }

    public CommonManageReply getRepInfo() {
      return this.repInfo;
    }

    public ServiceReply_args setRepInfo(CommonManageReply repInfo) {
      this.repInfo = repInfo;
      return this;
    }

    public void unsetRepInfo() {
      this.repInfo = null;
    }

    /** Returns true if field repInfo is set (has been assigned a value) and false otherwise */
    public boolean isSetRepInfo() {
      return this.repInfo != null;
    }

    public void setRepInfoIsSet(boolean value) {
      if (!value) {
        this.repInfo = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case REP_INFO:
        if (value == null) {
          unsetRepInfo();
        } else {
          setRepInfo((CommonManageReply)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case REP_INFO:
        return getRepInfo();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case REP_INFO:
        return isSetRepInfo();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof ServiceReply_args)
        return this.equals((ServiceReply_args)that);
      return false;
    }

    public boolean equals(ServiceReply_args that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_repInfo = true && this.isSetRepInfo();
      boolean that_present_repInfo = true && that.isSetRepInfo();
      if (this_present_repInfo || that_present_repInfo) {
        if (!(this_present_repInfo && that_present_repInfo))
          return false;
        if (!this.repInfo.equals(that.repInfo))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetRepInfo()) ? 131071 : 524287);
      if (isSetRepInfo())
        hashCode = hashCode * 8191 + repInfo.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(ServiceReply_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetRepInfo()).compareTo(other.isSetRepInfo());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetRepInfo()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.repInfo, other.repInfo);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("ServiceReply_args(");
      boolean first = true;

      sb.append("repInfo:");
      if (this.repInfo == null) {
        sb.append("null");
      } else {
        sb.append(this.repInfo);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (repInfo != null) {
        repInfo.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class ServiceReply_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public ServiceReply_argsStandardScheme getScheme() {
        return new ServiceReply_argsStandardScheme();
      }
    }

    private static class ServiceReply_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<ServiceReply_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, ServiceReply_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
            break;
          }
          switch (schemeField.id) {
            case 1: // REP_INFO
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.repInfo = new CommonManageReply();
                struct.repInfo.read(iprot);
                struct.setRepInfoIsSet(true);
              } else {
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, ServiceReply_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.repInfo != null) {
          oprot.writeFieldBegin(REP_INFO_FIELD_DESC);
          struct.repInfo.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class ServiceReply_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public ServiceReply_argsTupleScheme getScheme() {
        return new ServiceReply_argsTupleScheme();
      }
    }

    private static class ServiceReply_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<ServiceReply_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, ServiceReply_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetRepInfo()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetRepInfo()) {
          struct.repInfo.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, ServiceReply_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.repInfo = new CommonManageReply();
          struct.repInfo.read(iprot);
          struct.setRepInfoIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class ServiceReqAndReply_args implements org.apache.thrift.TBase<ServiceReqAndReply_args, ServiceReqAndReply_args._Fields>, java.io.Serializable, Cloneable, Comparable<ServiceReqAndReply_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ServiceReqAndReply_args");

    private static final org.apache.thrift.protocol.TField REQ_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("reqInfo", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ServiceReqAndReply_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ServiceReqAndReply_argsTupleSchemeFactory();

    public CommonManageReqInfo reqInfo; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      REQ_INFO((short)1, "reqInfo");

      private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // REQ_INFO
            return REQ_INFO;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.REQ_INFO, new org.apache.thrift.meta_data.FieldMetaData("reqInfo", org.apache.thrift.TFieldRequirementType.DEFAULT,
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CommonManageReqInfo.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ServiceReqAndReply_args.class, metaDataMap);
    }

    public ServiceReqAndReply_args() {
    }

    public ServiceReqAndReply_args(
      CommonManageReqInfo reqInfo)
    {
      this();
      this.reqInfo = reqInfo;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ServiceReqAndReply_args(ServiceReqAndReply_args other) {
      if (other.isSetReqInfo()) {
        this.reqInfo = new CommonManageReqInfo(other.reqInfo);
      }
    }

    public ServiceReqAndReply_args deepCopy() {
      return new ServiceReqAndReply_args(this);
    }

    @Override
    public void clear() {
      this.reqInfo = null;
    }

    public CommonManageReqInfo getReqInfo() {
      return this.reqInfo;
    }

    public ServiceReqAndReply_args setReqInfo(CommonManageReqInfo reqInfo) {
      this.reqInfo = reqInfo;
      return this;
    }

    public void unsetReqInfo() {
      this.reqInfo = null;
    }

    /** Returns true if field reqInfo is set (has been assigned a value) and false otherwise */
    public boolean isSetReqInfo() {
      return this.reqInfo != null;
    }

    public void setReqInfoIsSet(boolean value) {
      if (!value) {
        this.reqInfo = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case REQ_INFO:
        if (value == null) {
          unsetReqInfo();
        } else {
          setReqInfo((CommonManageReqInfo)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case REQ_INFO:
        return getReqInfo();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case REQ_INFO:
        return isSetReqInfo();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof ServiceReqAndReply_args)
        return this.equals((ServiceReqAndReply_args)that);
      return false;
    }

    public boolean equals(ServiceReqAndReply_args that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_reqInfo = true && this.isSetReqInfo();
      boolean that_present_reqInfo = true && that.isSetReqInfo();
      if (this_present_reqInfo || that_present_reqInfo) {
        if (!(this_present_reqInfo && that_present_reqInfo))
          return false;
        if (!this.reqInfo.equals(that.reqInfo))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetReqInfo()) ? 131071 : 524287);
      if (isSetReqInfo())
        hashCode = hashCode * 8191 + reqInfo.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(ServiceReqAndReply_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetReqInfo()).compareTo(other.isSetReqInfo());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetReqInfo()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reqInfo, other.reqInfo);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("ServiceReqAndReply_args(");
      boolean first = true;

      sb.append("reqInfo:");
      if (this.reqInfo == null) {
        sb.append("null");
      } else {
        sb.append(this.reqInfo);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (reqInfo != null) {
        reqInfo.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class ServiceReqAndReply_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public ServiceReqAndReply_argsStandardScheme getScheme() {
        return new ServiceReqAndReply_argsStandardScheme();
      }
    }

    private static class ServiceReqAndReply_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<ServiceReqAndReply_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, ServiceReqAndReply_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
            break;
          }
          switch (schemeField.id) {
            case 1: // REQ_INFO
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.reqInfo = new CommonManageReqInfo();
                struct.reqInfo.read(iprot);
                struct.setReqInfoIsSet(true);
              } else {
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, ServiceReqAndReply_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.reqInfo != null) {
          oprot.writeFieldBegin(REQ_INFO_FIELD_DESC);
          struct.reqInfo.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class ServiceReqAndReply_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public ServiceReqAndReply_argsTupleScheme getScheme() {
        return new ServiceReqAndReply_argsTupleScheme();
      }
    }

    private static class ServiceReqAndReply_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<ServiceReqAndReply_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, ServiceReqAndReply_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetReqInfo()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetReqInfo()) {
          struct.reqInfo.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, ServiceReqAndReply_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.reqInfo = new CommonManageReqInfo();
          struct.reqInfo.read(iprot);
          struct.setReqInfoIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class ServiceReqAndReply_result implements org.apache.thrift.TBase<ServiceReqAndReply_result, ServiceReqAndReply_result._Fields>, java.io.Serializable, Cloneable, Comparable<ServiceReqAndReply_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ServiceReqAndReply_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ServiceReqAndReply_resultStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ServiceReqAndReply_resultTupleSchemeFactory();

    public CommonManageReply success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT,
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CommonManageReply.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ServiceReqAndReply_result.class, metaDataMap);
    }

    public ServiceReqAndReply_result() {
    }

    public ServiceReqAndReply_result(
      CommonManageReply success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ServiceReqAndReply_result(ServiceReqAndReply_result other) {
      if (other.isSetSuccess()) {
        this.success = new CommonManageReply(other.success);
      }
    }

    public ServiceReqAndReply_result deepCopy() {
      return new ServiceReqAndReply_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public CommonManageReply getSuccess() {
      return this.success;
    }

    public ServiceReqAndReply_result setSuccess(CommonManageReply success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((CommonManageReply)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof ServiceReqAndReply_result)
        return this.equals((ServiceReqAndReply_result)that);
      return false;
    }

    public boolean equals(ServiceReqAndReply_result that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetSuccess()) ? 131071 : 524287);
      if (isSetSuccess())
        hashCode = hashCode * 8191 + success.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(ServiceReqAndReply_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("ServiceReqAndReply_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (success != null) {
        success.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class ServiceReqAndReply_resultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public ServiceReqAndReply_resultStandardScheme getScheme() {
        return new ServiceReqAndReply_resultStandardScheme();
      }
    }

    private static class ServiceReqAndReply_resultStandardScheme extends org.apache.thrift.scheme.StandardScheme<ServiceReqAndReply_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, ServiceReqAndReply_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new CommonManageReply();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, ServiceReqAndReply_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class ServiceReqAndReply_resultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public ServiceReqAndReply_resultTupleScheme getScheme() {
        return new ServiceReqAndReply_resultTupleScheme();
      }
    }

    private static class ServiceReqAndReply_resultTupleScheme extends org.apache.thrift.scheme.TupleScheme<ServiceReqAndReply_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, ServiceReqAndReply_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, ServiceReqAndReply_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = new CommonManageReply();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

}
